events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
    # Redirect ngrok landing page to app root
    location = /index.html {
        try_files $uri $uri/ /skip-ngrok.html;
    }
    }
}
