# Unique identifier for your SonarQube project
sonar.projectKey=CloudCart-DevSecOps-Platform

# The name that will show up in your SonarQube dashboard
sonar.projectName=CloudCart Platform

# Targets the exact folders containing your application code, infrastructure, and GitOps manifests
sonar.sources=app/frontend,infra,gitops

# Encoding of the source files
sonar.sourceEncoding=UTF-8
