# Unique identifier for your SonarQube project
sonar.projectKey=CloudCart-DevSecOps-Platform

# The name that will show up in your SonarQube dashboard
sonar.projectName=CloudCart Platform

# Tell Sonar to scan the app folder (frontend) and other source directories
sonar.sources=app,infra,gitops

# Encoding of the source files
sonar.sourceEncoding=UTF-8
