replicaCount: 1

image:
  repository: eswar2506/cloudcart-frontend
  tag: "df0b6d68741d90c91c20181e8964b35cd3ce26fc"
  pullPolicy: Always
service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

config:
  APP_NAME: CloudCart
  ENVIRONMENT: dev
  LOG_LEVEL: info

secret:
  DB_USERNAME: admin
  DB_PASSWORD: password123

# Change 'hpa:' to 'autoscaling:'
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
