replicaCount: 1

image:
  repository: eswar2506/cloudcart-frontend
  tag: "d1701dce5cb07c75f3dbf0736a71e70a1980cfab"
  pullPolicy: Always
service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

config:
  APP_NAME: CloudCart
  ENVIRONMENT: dev
  LOG_LEVEL: info

secret:
  DB_USERNAME: admin
  DB_PASSWORD: password123

# Change 'hpa:' to 'autoscaling:'
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
