apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudcart-config

data:
  APP_NAME: "{{ .Values.config.APP_NAME }}"
  ENVIRONMENT: "{{ .Values.config.ENVIRONMENT }}"
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL }}"
