apiVersion: v1
kind: Service
metadata:
  name: cloudcart-frontend
spec:
  type: {{ .Values.service.type }}   # Fixed: No space inside curly braces
  selector:
    app: cloudcart-frontend
  ports:
    - port: {{ .Values.service.port }} # Fixed: No space inside curly braces
      targetPort: 80
