name: CloudCart Unified DevSecOps Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cloudcart-frontend

jobs:
  devsecops-pipeline:
    name: Code Quality, Security Scan, and Continuous Delivery
    runs-on: ubuntu-latest

    steps:

      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. SonarQube Code Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: 3. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4. Build Security Test Image
        run: |
          docker build \
            -t cloudcart-frontend:${{ github.sha }} \
            ./app/frontend

      - name: 5. Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: 'cloudcart-frontend:${{ github.sha }}'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: 6. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: 7. Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: 8. Build and Push Production Image
        uses: docker/build-push-action@v6
        with:
          context: ./app/frontend
          push: true
          tags: |
            124502390077.dkr.ecr.ap-south-1.amazonaws.com/cloudcart-frontend:${{ github.sha }}
            124502390077.dkr.ecr.ap-south-1.amazonaws.com/cloudcart-frontend:latest

      - name: 9. Update Helm Image
        run: |
          sed -i -E "s|(^[[:space:]]*repository:[[:space:]]*).*|\1124502390077.dkr.ecr.ap-south-1.amazonaws.com/cloudcart-frontend|g" helm/cloudcart/values.yaml
          sed -i -E "s|(^[[:space:]]*tag:[[:space:]]*).*|\1\"${{ github.sha }}\"|g" helm/cloudcart/values.yaml

      - name: 10. Show Updated Helm Values
        run: |
          cat helm/cloudcart/values.yaml

      - name: 11. Commit Helm GitOps Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/cloudcart/values.yaml
          git commit -m "chore(gitops): update frontend image to ${{ github.sha }} [skip ci]" || true
          git push
